# Generated by Django 5.2.10 on 2026-02-02 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('ML', 'MASAL'), ('GN', 'GINGER'), ('NM', 'NORMAL')], max_length=2)),
            ],
        ),
    ]
